@tokenapp = 7|KuzT0jnKrzAx8y4zd8qQapQPjtsttLMpRbKwJKFB

### HTTP Request to login to the application
### Login Request
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "password"
}

### logout Request
POST http://localhost:8000/api/logout
Content-Type: application/json
Authorization: Bearer {{tokenapp}}

### Get all offices Request
GET http://localhost:8000/api/offices
Content-Type: application/json
Authorization: Bearer {{tokenapp}}

### get all user Request
GET http://localhost:8000/api/user
Content-Type: application/json
Authorization: Bearer {{tokenapp}}

### get all users Request
GET http://localhost:8000/api/users
Content-Type: application/json
Authorization: Bearer {{tokenapp}}

### obtener todos los equipos Request
GET http://localhost:8000/api/equipment
Content-Type: application/json
Authorization: Bearer {{tokenapp}}

### obtener todas oficinas
GET http://localhost:8000/api/offices
Content-Type: application/json
Authorization: Bearer {{tokenapp}}